# Generated by Django 4.2.2 on 2023-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_main', models.CharField(max_length=155, verbose_name='Основная опция')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(default='', verbose_name='Описание продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=150, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='', max_length=150, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview', verbose_name='Заставка'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(default=0, verbose_name='Артикул'),
        ),
        migrations.CreateModel(
            name='ProductOptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Опция')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productoption')),
            ],
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.product'),
        ),
    ]
