# Generated by Django 4.2.2 on 2023-08-14 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productoption_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'Основная характеристика', 'verbose_name_plural': 'Основные характеристики'},
        ),
        migrations.AlterModelOptions(
            name='productoptionitem',
            options={'verbose_name': 'Дополнительная характеристика', 'verbose_name_plural': 'Дополнительные характеристики'},
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_main',
            field=models.CharField(max_length=155, verbose_name='Основная характеристика'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.product', verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='productoptionitem',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Дополнительная характеристика'),
        ),
        migrations.AlterField(
            model_name='productoptionitem',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='api.productoption'),
        ),
    ]
