# Generated by Django 4.2.2 on 2023-07-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="", max_length=150, verbose_name="Бренд"),
        ),
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(default="", max_length=150, verbose_name="Пол"),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor_code",
            field=models.IntegerField(default=0, verbose_name="Артикул"),
        ),
    ]
