# Generated by Django 4.2.2 on 2023-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default='', max_length=150, verbose_name='Артикул'),
        ),
    ]
