# Generated by Django 4.2.2 on 2023-08-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_options_alter_productoptionitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='svg_file',
            field=models.FileField(null=True, upload_to='categories/icons/'),
        ),
    ]
