# Generated by Django 4.2.2 on 2023-08-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productcharacteristicstitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristicstitle',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductCharacteristicsOptions',
        ),
        migrations.DeleteModel(
            name='ProductCharacteristicsTitle',
        ),
    ]
