# Generated by Django 4.2.2 on 2023-08-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_svg_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='svg_file',
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(default='', upload_to='photos/categories/', verbose_name='Фото категории'),
        ),
    ]
