# Generated by Django 4.2.2 on 2023-08-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_category_svg_file_alter_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(null=True, upload_to='products/video/', verbose_name='Видео'),
        ),
    ]
