# Generated by Django 4.2.2 on 2023-08-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_categorycharacteristicsoptions_category_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycharacteristicsoptions',
            name='category_characteristics',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.categorycharacteristics'),
        ),
        migrations.AlterField(
            model_name='categorycharacteristicsoptions',
            name='option',
            field=models.CharField(default='', max_length=150),
        ),
    ]
