# Generated by Django 4.2.2 on 2023-08-10 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_categorycharacteristicsoptions_category_characteristics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycharacteristics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='api.product'),
        ),
    ]
