# Generated by Django 4.2.2 on 2023-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_product_video_category_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoptionitem",
            name="name",
            field=models.TextField(
                default="", verbose_name="Дополнительная характеристика"
            ),
        ),
    ]
