# Generated by Django 4.2.2 on 2023-08-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_categorycharacteristicsoptions_category_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycharacteristicsoptions',
            name='category_characteristics',
        ),
        migrations.AddField(
            model_name='categorycharacteristicsoptions',
            name='product_characteristics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.product'),
        ),
    ]
