# Generated by Django 4.2.2 on 2023-08-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_categorycharacteristicsoptions_category_characteristics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorycharacteristicsoptions',
            old_name='product_characteristics',
            new_name='product',
        ),
    ]
