# Generated by Django 4.2.2 on 2023-11-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_category_video_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
