# Generated by Django 4.2.2 on 2023-08-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_product_characteristics_categorycharacteristicsoptions_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycharacteristics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='api.product'),
        ),
        migrations.AlterField(
            model_name='categorycharacteristicsoptions',
            name='product',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.product'),
        ),
    ]
