# Generated by Django 4.2.2 on 2023-08-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_categorycharacteristics_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycharacteristicsoptions',
            name='product',
        ),
        migrations.DeleteModel(
            name='CategoryCharacteristics',
        ),
        migrations.DeleteModel(
            name='CategoryCharacteristicsOptions',
        ),
    ]
