# Generated by Django 4.2.2 on 2023-11-26 15:28

import api.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to=api.models.ProductImage.make_folder_path, verbose_name='Фото продукта'),
        ),
    ]
