# Generated by Django 4.2.2 on 2023-08-13 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_categorycharacteristicsoptions_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=155, verbose_name='Название категории характеристики')),
                ('option', models.CharField(max_length=155, verbose_name='Название характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.product')),
            ],
        ),
    ]
