# Generated by Django 4.2.2 on 2023-08-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_productcharacteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristics',
            name='category',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Название категории характеристики'),
        ),
    ]
