# Generated by Django 4.2.2 on 2023-08-13 10:09

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_productcharacteristics_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='productcharacteristics',
            name='category',
            field=models.CharField(blank=True, help_text='Добавьте один элемент, затем его подпункты', max_length=155, null=True, verbose_name='Название категории характеристики'),
        ),
    ]
