# Generated by Django 4.2.2 on 2023-08-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_testmodel_alter_productcharacteristics_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
