# Generated by Django 4.2.2 on 2023-08-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_productcharacteristics_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Опция')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Оглавление опции')),
                ('options', models.ManyToManyField(through='api.ProductCharacteristics', to='api.productoption')),
            ],
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productoption'),
        ),
        migrations.AddField(
            model_name='productcharacteristics',
            name='product_option_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productoptioncategory'),
        ),
    ]
