# Generated by Django 4.2.2 on 2023-08-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_productcharacteristics_productoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristics',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
