# Generated by Django 4.2.2 on 2023-08-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_productcharacteristics_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoptioncategory',
            name='options',
        ),
        migrations.DeleteModel(
            name='ProductCharacteristics',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductOptionCategory',
        ),
    ]
